<?php
/*
 * @Description: 
 * @Author: chenxf
 * @LastEditors: chenxf
 * @Date: 2019/12/17
 * @Time: 20:45
 */

return [
    array(
        'module' => 'admin',
        'permission' => 'admin::system/default',
        'url' => '',
        'name' => '常规管理',
        'icon' => 'fas fa-cogs',
        'type' => 1,
        'status' => 1,
        'remark' => '常规管理',
        'sort' => 0,
        'children' =>
        array(
            array(
                'module' => 'admin',
                'permission' => 'admin::system/SiteController@index',
                'url' => '/admin/site/index',
                'name' => '系统配置',
                'icon' => 'fa fa-cog',
                'type' => 1,
                'status' => 1,
                'remark' => '系统配置页面',
                'sort' => 1,
                'children' =>
                array(
                  array(
                      'module' => 'admin',
                      'permission' => 'admin::system/SiteController@set',
                      'url' => '',
                      'name' => '系统配置',
                      'icon' => 'far fa-circle',
                      'type' => 1,
                      'status' => 0,
                      'remark' => '系统配置操作',
                      'sort' => 0,
                  )
                ),
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::system/MenuController@index',
                'url' => '/admin/menu',
                'name' => '菜单管理',
                'icon' => 'fa fa-th',
                'type' => 1,
                'status' => 1,
                'remark' => '菜单管理',
                'sort' => 2,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::system/MenuController@create',
                            'url' => '',
                            'name' => '添加菜单',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '添加后台菜单',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::system/MenuController@edit',
                            'url' => '',
                            'name' => '编辑菜单',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '编辑后台菜单',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::system/MenuController@destroy',
                            'url' => '',
                            'name' => '删除菜单',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '删除后台菜单',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::system/MenuController@show',
                            'url' => '',
                            'name' => '菜单详情',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '菜单详情',
                            'sort' => 0,
                        ),
                    )
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::system/PersonController@index',
                'url' => '/admin/person/index',
                'name' => '个人资料',
                'icon' => 'fa fa-user',
                'type' => 1,
                'status' => 1,
                'remark' => '个人资料',
                'sort' => 3,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::system/PersonController@update',
                            'url' => '',
                            'name' => '修改个人信息',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '修改个人信息',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::system/PersonController@reset',
                            'url' => '',
                            'name' => '修改密码',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '修改密码',
                            'sort' => 0,
                        ),
                    )
            ),
        )
    ),
    array(
        'module' => 'admin',
        'permission' => 'admin::permission/admin',
        'url' => '',
        'name' => '权限管理',
        'icon' => 'fas fa-users',
        'type' => 1,
        'status' => 1,
        'remark' => '权限管理',
        'sort' => 0,
        'children' =>
            array(
                array(
                    'module' => 'admin',
                    'permission' => 'admin::permission/RoleController@index',
                    'url' => '/admin/role',
                    'name' => '角色列表',
                    'icon' => 'fa fa-bars',
                    'type' => 1,
                    'status' => 1,
                    'remark' => '角色列表',
                    'sort' => 0,
                    'children' =>
                        array(
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/RoleController@create',
                                'url' => '',
                                'name' => '添加角色',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '添加角色',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/RoleController@edit',
                                'url' => '',
                                'name' => '编辑角色',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '编辑角色',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/RoleController@destroy',
                                'url' => '',
                                'name' => '删除角色',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '删除角色',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/RoleController@permission',
                                'url' => '',
                                'name' => '权限设置',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '权限设置',
                                'sort' => 0,
                            ),
                        )
                ),
                array(
                    'module' => 'admin',
                    'permission' => 'admin::permission/AdminController@index',
                    'url' => '/admin/admin',
                    'name' => '管理员',
                    'icon' => 'fa fa-user-plus',
                    'type' => 1,
                    'status' => 1,
                    'remark' => '管理员列表',
                    'sort' => 0,
                    'children' =>
                        array(
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/AdminController@create',
                                'url' => '',
                                'name' => '添加管理员',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '添加管理员',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/AdminController@edit',
                                'url' => '',
                                'name' => '编辑管理员',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '编辑管理员',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/AdminController@destroy',
                                'url' => '',
                                'name' => '删除管理员',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '删除管理员',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/AdminController@forbidden',
                                'url' => '',
                                'name' => '拉黑管理员',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '拉黑管理员',
                                'sort' => 0,
                            ),
                            array(
                                'module' => 'admin',
                                'permission' => 'admin::permission/AdminController@enable',
                                'url' => '',
                                'name' => '启用管理员',
                                'icon' => 'far fa-circle',
                                'type' => 1,
                                'status' => 0,
                                'remark' => '启用管理员',
                                'sort' => 0,
                            ),
                        )
                ),
            )
    ),
    array(
        'module' => 'admin',
        'permission' => 'admin::user/default',
        'url' => '',
        'name' => '用户管理',
        'icon' => 'fas fa-user-plus',
        'type' => 1,
        'status' => 1,
        'remark' => '用户管理',
        'sort' => 0,
        'children' =>
            array(
                array(
                    'module' => 'admin',
                    'permission' => 'admin::user/UserController@index',
                    'url' => '/admin/user/index',
                    'name' => '本站用户',
                    'icon' => 'far fa-circle text-success',
                    'type' => 1,
                    'status' => 1,
                    'remark' => '本站用户',
                    'sort' => 0,
                ),
                array(
                    'module' => 'admin',
                    'permission' => 'admin::user/UserController@indexauth',
                    'url' => '',
                    'name' => '第三方用户',
                    'icon' => 'far fa-circle text-danger',
                    'type' => 1,
                    'status' => 1,
                    'remark' => '第三方用户',
                    'sort' => 0,
                ),
            )
    ),
    array(
        'module' => 'admin',
        'permission' => 'admin::portal/default',
        'url' => '',
        'name' => '内容管理',
        'icon' => 'fas fa-list',
        'type' => 1,
        'status' => 1,
        'remark' => '内容管理',
        'sort' => 0,
        'children' =>
        array(
            array(
                'module' => 'admin',
                'permission' => 'admin::portal/CategoryController@index',
                'url' => '/admin/category',
                'name' => '栏目管理',
                'icon' => 'fas fa-briefcase',
                'type' => 1,
                'status' => 1,
                'remark' => '栏目管理',
                'sort' => 0,
                'children' =>
                array(
                    array(
                        'module' => 'admin',
                        'permission' => 'admin::portal/CategoryController@create',
                        'url' => '',
                        'name' => '添加栏目',
                        'icon' => 'far fa-circle',
                        'type' => 1,
                        'status' => 0,
                        'remark' => '添加栏目',
                        'sort' => 0,
                    ),
                    array(
                        'module' => 'admin',
                        'permission' => 'admin::portal/CategoryController@edit',
                        'url' => '',
                        'name' => '编辑栏目',
                        'icon' => 'far fa-circle',
                        'type' => 1,
                        'status' => 0,
                        'remark' => '编辑栏目',
                        'sort' => 0,
                    ),
                    array(
                        'module' => 'admin',
                        'permission' => 'admin::portal/CategoryController@destroy',
                        'url' => '',
                        'name' => '删除栏目',
                        'icon' => 'far fa-circle',
                        'type' => 1,
                        'status' => 0,
                        'remark' => '删除栏目',
                        'sort' => 0,
                    ),
                ),
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::portal/ArticleController@default',
                'url' => '',
                'name' => '文章管理',
                'icon' => 'fas fa-book',
                'type' => 1,
                'status' => 1,
                'remark' => '文章管理',
                'sort' => 0,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/ArticleController@index',
                            'url' => '/admin/article',
                            'name' => '文章列表',
                            'icon' => 'fa fa-align-justify',
                            'type' => 1,
                            'status' => 1,
                            'remark' => '文章列表',
                            'sort' => 0,
                            'children' =>
                            array(
                                array(
                                    'module' => 'admin',
                                    'permission' => 'admin::portal/ArticleController@edit',
                                    'url' => '',
                                    'name' => '编辑文章',
                                    'icon' => 'far fa-circle',
                                    'type' => 1,
                                    'status' => 0,
                                    'remark' => '编辑文章',
                                    'sort' => 0,
                                ),
                                array(
                                    'module' => 'admin',
                                    'permission' => 'admin::portal/ArticleController@destroy',
                                    'url' => '',
                                    'name' => '删除文章',
                                    'icon' => 'far fa-circle',
                                    'type' => 1,
                                    'status' => 0,
                                    'remark' => '删除文章',
                                    'sort' => 0,
                                ),
                            ),
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/ArticleController@create',
                            'url' => '/admin/article/create',
                            'name' => '撰写文章',
                            'icon' => 'fa fa-pencil-alt',
                            'type' => 1,
                            'status' => 1,
                            'remark' => '撰写文章',
                            'sort' => 0,
                            'children' =>
                            array(
                                array(
                                    'module' => 'admin',
                                    'permission' => 'admin::portal/ArticleController@store',
                                    'url' => '',
                                    'name' => '发布文章',
                                    'icon' => 'far fa-circle',
                                    'type' => 1,
                                    'status' => 1,
                                    'remark' => '发布文章',
                                    'sort' => 0,
                                ),
                            ),
                        ),
                    ),
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::portal/ItemController@index',
                'url' => '/admin/item',
                'name' => '分类管理',
                'icon' => 'fas fa-th-list',
                'type' => 1,
                'status' => 1,
                'remark' => '分类管理',
                'sort' => 0,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/ItemController@create',
                            'url' => '',
                            'name' => '添加分类',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '添加分类',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/ItemController@edit',
                            'url' => '',
                            'name' => '编辑分类',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '编辑分类',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/ItemController@destroy',
                            'url' => '',
                            'name' => '删除分类',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '删除分类',
                            'sort' => 0,
                        ),
                    ),
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::portal/TagController@index',
                'url' => '/admin/tag',
                'name' => '标签管理',
                'icon' => 'fas fa-tags',
                'type' => 1,
                'status' => 1,
                'remark' => '标签管理',
                'sort' => 0,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/TagController@create',
                            'url' => '',
                            'name' => '添加标签',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '添加标签',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/TagController@edit',
                            'url' => '',
                            'name' => '编辑标签',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '编辑标签',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/TagController@destroy',
                            'url' => '',
                            'name' => '删除标签',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '删除标签',
                            'sort' => 0,
                        ),
                    ),
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::portal/LinkController@index',
                'url' => '/admin/link',
                'name' => '链接管理',
                'icon' => 'fas fa-link',
                'type' => 1,
                'status' => 1,
                'remark' => '链接管理',
                'sort' => 0,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/LinkController@create',
                            'url' => '',
                            'name' => '添加链接',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '添加链接',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/LinkController@edit',
                            'url' => '',
                            'name' => '编辑链接',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '编辑链接',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/LinkController@destroy',
                            'url' => '',
                            'name' => '删除链接',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '删除链接',
                            'sort' => 0,
                        ),
                    ),
            ),
            array(
                'module' => 'admin',
                'permission' => 'admin::portal/SlideController@index',
                'url' => '/admin/slide',
                'name' => '幻灯片管理',
                'icon' => 'fas fa-sliders',
                'type' => 1,
                'status' => 1,
                'remark' => '幻灯片管理',
                'sort' => 0,
                'children' =>
                    array(
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/SlideController@create',
                            'url' => '',
                            'name' => '添加幻灯片',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '添加幻灯片',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/SlideController@edit',
                            'url' => '',
                            'name' => '编辑幻灯片',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '编辑幻灯片',
                            'sort' => 0,
                        ),
                        array(
                            'module' => 'admin',
                            'permission' => 'admin::portal/SlideController@destroy',
                            'url' => '',
                            'name' => '删除幻灯片',
                            'icon' => 'far fa-circle',
                            'type' => 1,
                            'status' => 0,
                            'remark' => '删除幻灯片',
                            'sort' => 0,
                        ),
                    ),
            ),
        ),
    ),
    array(
        'module' => 'admin',
        'permission' => 'admin::resource/default',
        'url' => '',
        'name' => '资源管理',
        'icon' => 'fas fa-database',
        'type' => 1,
        'status' => 1,
        'remark' => '资源管理',
        'sort' => 0,
        'children' =>
        array(
            array(
                'module' => 'admin',
                'permission' => 'admin::resource/@StorageController@index',
                'url' => '/admin/index',
                'name' => '资源列表',
                'icon' => 'fa fa-list',
                'type' => 1,
                'status' => 1,
                'remark' => '资源列表',
                'sort' => 0,
            ),
        )
    ),
];